services:
  postgres:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:-app}
      POSTGRES_PASSWORD: ${PGPASSWORD:-secret}
      POSTGRES_DB: ${PGDATABASE:-appdb}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      UVICORN_HOST: ${UVICORN_HOST:-0.0.0.0}
      UVICORN_PORT: ${UVICORN_PORT:-8000}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${UVICORN_PORT:-8000}:${UVICORN_PORT:-8000}"
    command: bash -c "while !</dev/tcp/postgres/5432; \
      do sleep 1; \
      done; \
      cd src; \
      poetry run uvicorn start:app"
    healthcheck:
      test: ["CMD-SHELL", "curl web:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: